### ISSUE TITLE
BUG - Odata v2 eeponse returned by ui5-middleware-fe-mockserver cause URIError

### ISSUE THREAD

**Issue by LombardsAI** [SAP/open-ux-odata#680] opened 2023-08-23 07:38 UTC
### Description
When the key of a request instance contains "%", the response returned by ui5-middleware-fe-mockserver will be something like:
```
{
                "name": "%(m)",
                "descr": "Percent mass",
                "code": "M%",
                "__metadata": {
                    "id": "/odata/v2/PropertyConfigureService/UnitOfMeasure('M%')",
                    "uri": "/odata/v2/PropertyConfigureService/UnitOfMeasure('M%')",
                    "type": "PropertyConfigureService.UnitOfMeasure"
                }
            }
```
in which the _metadata part will cause a URIError because of ('M%'), please see the screenshot below:
![image](https://github.com/SAP/open-ux-odata/assets/44212466/88d34f45-d5b5-4b0d-82f7-6181c2aaf831)

As a reference, the response in our Dev environment will be something like:
```
"__metadata": {
                    "id": "https://epd-acc-eu20-consumer.specification-management.eu20.acc.epd.dev.sap:443/odata/v2/PropertyConfigureService/UnitOfMeasure('M%25')",
                    "uri": "https://epd-acc-eu20-consumer.specification-management.eu20.acc.epd.dev.sap:443/odata/v2/PropertyConfigureService/UnitOfMeasure('M%25')",
                    "type": "PropertyConfigureService.UnitOfMeasure"
                }
```

#### Version/Components/Environment	
This issue happened when we want to upgrade @sap-ux/ui5-middleware-fe-mockserver from 2.1.98 to 2.1.115

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by metzing** [comment] 2023-09-05 13:38
Hello Colleagues,

This issue is blocking us from keeping up-to-date with the `@sap-ux/ui5-middleware-fe-mockserver` package.

Can we have a reply here please? Do you need any additional information?

Thanks,
Marton

**Comment by nlunets** [comment] 2023-09-06 09:04
Should be fixed with [@sap-ux/ui5-middleware-fe-mockserver@2.1.120]

**Closed by nlunets** 2023-09-06 09:04 UTC

**Comment by metzing** [comment] 2023-09-06 13:45
Thanks, checking

**Comment by metzing** [comment] 2023-09-06 14:06
Original issue seems to be resolved, but now we have another test failing with the upgrade 😅 Thanks for the assistance here, I'll investigate and open a new issue if applicable.

**Comment by metzing** [comment] 2023-09-20 15:14
Thanks, the fix is confirmed
